[package]
name = "peyvand"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "=4.5.*", features = ["derive"] }
spdlog-rs = "0.4.*"
anyhow = "1.0.*"
signal-hook = {version = "0.3.*", features = ["extended-siginfo"] }
libc = "0.2.*"
tao = "0.34.*"
wry = "0.53.*"
wgpu = "26.0.*"
